# Generated by Django 6.0.7 on 2026-07-08 08:29

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('theme', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=apps.events.models.event_banner_path)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.events.models.event_logo_path)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_open_date', models.DateTimeField(blank=True, null=True)),
                ('registration_close_date', models.DateTimeField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('not_open', 'Not Open'), ('open', 'Open'), ('closed', 'Closed')], default='not_open', max_length=10)),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited.', null=True)),
                ('color_theme', models.CharField(default='#7C3AED', max_length=7)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ['-year', '-start_date'],
                'indexes': [models.Index(fields=['year'], name='events_even_year_f60a43_idx'), models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx')],
            },
        ),
    ]
