# Generated by Django 6.0.7 on 2026-07-08 08:29

import apps.people.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('person_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('qr_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.people.models.person_photo_path)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('residential_address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('local_government', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('church_name', models.CharField(blank=True, max_length=255)),
                ('church_address', models.TextField(blank=True)),
                ('pastors_name', models.CharField(blank=True, max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_relationship', models.CharField(blank=True, max_length=100)),
                ('medical_notes', models.TextField(blank=True)),
                ('dietary_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('flagged', 'Flagged')], default='active', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='people_pers_phone_n_0903c0_idx'), models.Index(fields=['email_address'], name='people_pers_email_a_ede55b_idx'), models.Index(fields=['person_id'], name='people_pers_person__b6316a_idx')],
            },
        ),
    ]
