# Generated by Django 6.0.7 on 2026-07-10 00:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('events', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('registration_confirmation', 'Registration Confirmation'), ('reminder', 'Reminder Email'), ('accommodation_info', 'Accommodation Information'), ('conference_schedule', 'Conference Schedule'), ('thank_you', 'Thank You Email'), ('follow_up', 'Follow-up Email'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Plain text or simple HTML. Use placeholders like {{ first_name }}, {{ event_title }}.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('target_category', models.CharField(blank=True, help_text="'participant', 'worker', or blank for both.", max_length=15)),
                ('target_worker_type', models.CharField(blank=True, help_text="'member', 'pastor', or blank for both.", max_length=10)),
                ('target_state', models.CharField(blank=True, max_length=100)),
                ('target_country', models.CharField(blank=True, max_length=100)),
                ('target_church_name', models.CharField(blank=True, help_text='Matches church name (contains).', max_length=255)),
                ('target_returning', models.CharField(choices=[('any', 'Anyone'), ('returning_only', 'Returning attendees only'), ('first_time_only', 'First-time attendees only')], default='any', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='For "Send Now", leave blank. For scheduled sending, set a future time — requires the send_due_campaigns management command to be run periodically (cron/Celery beat).', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Leave blank to target across every event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='events.event')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='departments.department')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_address', models.EmailField(help_text="Snapshot of the person's email at send time.", max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('opened', 'Opened')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('open_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.emailcampaign')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_recipient_entries', to='people.person')),
            ],
            options={
                'ordering': ['person__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_recipient_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'person'), name='unique_recipient_per_campaign'),
        ),
    ]
