# Generated by Django 6.0.7 on 2026-07-15 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("link_url", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_name", models.CharField(default="SEMS", max_length=100)),
                (
                    "church_name",
                    models.CharField(default="Again and Afresh Church", max_length=150),
                ),
                (
                    "church_logo",
                    models.ImageField(blank=True, null=True, upload_to="settings/"),
                ),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                (
                    "default_color_theme",
                    models.CharField(default="#D4A24C", max_length=7),
                ),
                (
                    "default_theme_mode",
                    models.CharField(
                        choices=[("dark", "Dark"), ("light", "Light")],
                        default="dark",
                        max_length=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-created_at"], name="core_auditl_created_1a76fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["model_name"], name="core_auditl_model_n_36490f_idx"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="read_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["-created_at"], name="core_notifi_created_f19d5e_idx"
            ),
        ),
    ]
