# Generated by Django 6.0.7 on 2026-07-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_notification_systemsettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="giving_url",
            field=models.URLField(
                blank=True,
                help_text="Where the public site's 'Give' button links to (e.g. a Paystack payment link or your existing giving page). Registration itself is always free — this is a voluntary link, not a payment gate. Leave blank to hide the button.",
            ),
        ),
    ]
