# Generated by Django 6.0.7 on 2026-07-18 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_systemsettings_giving_url"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="default_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Which event '/register/' and the public landing page resolve to when no slug is given — this is what makes the short, shareable URL possible (e.g. sycamore.againandafresh.org/register instead of /register/sycamore-2026/). Event-specific links (/register/<slug>/) keep working regardless, so other concurrent events can still be shared directly. Leave blank if nothing should resolve at the short URL yet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="events.event",
            ),
        ),
    ]
