# Generated by Django 6.0.7 on 2026-07-08 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('events', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('participant', 'Participant'), ('worker', 'Worker')], max_length=15)),
                ('worker_type', models.CharField(blank=True, choices=[('member', 'Member'), ('pastor', 'Pastor')], max_length=10)),
                ('is_returning_attendee', models.BooleanField(default=False, help_text="Answer to 'Have you attended any previous Sycamore Conference?' for this registration.")),
                ('accommodation_requested', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('waitlisted', 'Waitlisted')], default='pending', max_length=12)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='departments.department')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['registration_number'], name='registratio_registr_40a794_idx')],
                'constraints': [models.UniqueConstraint(fields=('person', 'event'), name='unique_person_per_event')],
            },
        ),
    ]
