# Generated by Django 6.0.7 on 2026-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="badge_label",
            field=models.CharField(
                blank=True,
                help_text="Overrides the category text printed on the ID card, e.g. 'VIP', 'Speaker', 'Volunteer'. Leave blank to print the category/worker type as-is.",
                max_length=30,
            ),
        ),
    ]
