# Generated by Django 6.0.7 on 2026-07-10 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow_up_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('sms', 'SMS'), ('prayer_request', 'Prayer Request'), ('counselling', 'Counselling'), ('transportation', 'Transportation'), ('accommodation', 'Accommodation'), ('church_membership', 'Church Membership'), ('other', 'Other')], max_length=20)),
                ('interest_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('reached', 'Reached'), ('no_response', 'No Response'), ('rescheduled', 'Rescheduled'), ('resolved', 'Resolved')], default='pending', max_length=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, help_text='Optional — which conference this follow-up relates to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='events.event')),
                ('logged_by', models.ForeignKey(blank=True, help_text='Who recorded this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_followups', to=settings.AUTH_USER_MODEL)),
                ('officer_assigned', models.ForeignKey(blank=True, help_text='Who is responsible for the next step.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['person', '-created_at'], name='followup_person_created_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status'], name='followup_status_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['next_follow_up_date'], name='followup_next_date_idx'),
        ),
    ]
